#ifndef INCLUDE_CONSTANTS_H
#define INCLUDE_CONSTANTS_H

// #define BASE_URL "http://192.168.1.221:3000/"
#define BASE_URL "http://statsapi.mlb.com/api/"
#define PANEL_WIDTH 64
#define PANEL_HEIGHT 32  	// Panel height of 64 will required PIN_E to be defined.
#define PANELS_NUMBER 1 	// Number of chained panels, if just a single panel, obviously set to 1
#define JSON_BUFFER_SIZE 2048
#define BOX_PADDING 2
#define HYDRATIONS_ARRAY_SIZE 32
#define FIELDS_ARRAY_SIZE 32

#include <map>

enum TEAM_ID {
    ATLANTA_BRAVES = 144,
    ARIZONA_DIAMONDBACKS = 109,
    BALTIMORE_ORIOLES = 110,
    BOSTON_REDSOX = 111,
    CHICAGO_CUBS = 112,
    CHICAGO_WHITE_SOX = 145,
    CINCINNATI_REDS = 113,
    CLEVELAND_INDIANS = 114,
    COLORADO_ROCKIES = 115,
    DETROIT_TIGERS = 116,
    HOUSTON_ASTROS = 117,
    KANSAS_CITY_ROYALS = 118,
    LOS_ANGELES_ANGELS = 108,
    LOS_ANGELES_DODGERS = 119,
    MIAMI_MARLINS = 146,
    MILWAUKEE_BREWERS = 158,
    MINNESOTA_TWINS = 142,
    NEW_YORK_METS = 121,
    NEW_YORK_YANKEES = 147,
    OAKLAND_ATHLETICS = 133,
    PHILADELPHIA_PHILLIES = 143,
    PITTSBURGH_PIRATES = 134,
    SAN_DIEGO_PADRES = 135,
    SAN_FRANCISCO_GIANTS = 137,
    SEATTLE_MARINERS = 136,
    ST_LOUIS_CARDINALS = 138,
    TAMPA_BAY_RAYS = 139,
    TEXAS_RANGERS = 140,
    TORONTO_BLUE_JAYS = 141,
    WASHINGTON_NATIONALS = 120
};

enum COLORS {
    RED = 0x8000,
    YELLOW = 0xFFE0,
    WHITE = 0xFFFF,
    BLACK = 0x0000,
    NAVY_BLUE = 0x000F,
    ROYAL_BLUE = 0x435C,
    ORANGE = 0xFD20,
    GREEN = 0x07E0,
    GRAY = 0x8410,
    BROWN = 0xA145,
    PURPLE = 0x8010
};

std::map<int, uint16_t> TEAM_BG_COLORS = {
    {TEAM_ID::ATLANTA_BRAVES, COLORS::NAVY_BLUE},
    {TEAM_ID::ARIZONA_DIAMONDBACKS, COLORS::RED},
    {TEAM_ID::BALTIMORE_ORIOLES, COLORS::ORANGE},
    {TEAM_ID::BOSTON_REDSOX, COLORS::RED},
    {TEAM_ID::CHICAGO_CUBS, COLORS::ROYAL_BLUE},
    {TEAM_ID::CHICAGO_WHITE_SOX, COLORS::BLACK},
    {TEAM_ID::CINCINNATI_REDS, COLORS::RED},
    {TEAM_ID::CLEVELAND_INDIANS, COLORS::NAVY_BLUE},
    {TEAM_ID::COLORADO_ROCKIES, COLORS::BLACK},
    {TEAM_ID::DETROIT_TIGERS, COLORS::BLACK},
    {TEAM_ID::HOUSTON_ASTROS, COLORS::ORANGE},
    {TEAM_ID::KANSAS_CITY_ROYALS, COLORS::ROYAL_BLUE},
    {TEAM_ID::LOS_ANGELES_ANGELS, COLORS::RED},
    {TEAM_ID::LOS_ANGELES_DODGERS, COLORS::ROYAL_BLUE},
    {TEAM_ID::MIAMI_MARLINS, COLORS::ROYAL_BLUE},
    {TEAM_ID::MILWAUKEE_BREWERS, COLORS::NAVY_BLUE},
    {TEAM_ID::MINNESOTA_TWINS, COLORS::NAVY_BLUE},
    {TEAM_ID::NEW_YORK_METS, COLORS::ROYAL_BLUE},
    {TEAM_ID::NEW_YORK_YANKEES, COLORS::GRAY},
    {TEAM_ID::OAKLAND_ATHLETICS, COLORS::GREEN},
    {TEAM_ID::PHILADELPHIA_PHILLIES, COLORS::RED},
    {TEAM_ID::PITTSBURGH_PIRATES, COLORS::BLACK},
    {TEAM_ID::SAN_DIEGO_PADRES, COLORS::BROWN},
    {TEAM_ID::SAN_FRANCISCO_GIANTS, COLORS::BLACK},
    {TEAM_ID::SEATTLE_MARINERS, COLORS::NAVY_BLUE},
    {TEAM_ID::ST_LOUIS_CARDINALS, COLORS::RED},
    {TEAM_ID::TAMPA_BAY_RAYS, COLORS::NAVY_BLUE},
    {TEAM_ID::TEXAS_RANGERS, COLORS::ROYAL_BLUE},
    {TEAM_ID::TORONTO_BLUE_JAYS, COLORS::ROYAL_BLUE},
    {TEAM_ID::WASHINGTON_NATIONALS, COLORS::RED}
};

std::map<int, uint16_t> TEAMS_TEXT_COLORS = {
    {TEAM_ID::ATLANTA_BRAVES, COLORS::RED},
    {TEAM_ID::ARIZONA_DIAMONDBACKS, COLORS::BLACK},
    {TEAM_ID::BALTIMORE_ORIOLES, COLORS::BLACK},
    {TEAM_ID::BOSTON_REDSOX, COLORS::WHITE},
    {TEAM_ID::CHICAGO_CUBS, COLORS::RED},
    {TEAM_ID::CHICAGO_WHITE_SOX, COLORS::WHITE},
    {TEAM_ID::CINCINNATI_REDS, COLORS::WHITE},
    {TEAM_ID::CLEVELAND_INDIANS, COLORS::RED},
    {TEAM_ID::COLORADO_ROCKIES, COLORS::PURPLE},
    {TEAM_ID::DETROIT_TIGERS, COLORS::WHITE},
    {TEAM_ID::HOUSTON_ASTROS, COLORS::NAVY_BLUE},
    {TEAM_ID::KANSAS_CITY_ROYALS, COLORS::WHITE},
    {TEAM_ID::LOS_ANGELES_ANGELS, COLORS::WHITE},
    {TEAM_ID::LOS_ANGELES_DODGERS, COLORS::WHITE},
    {TEAM_ID::MIAMI_MARLINS, COLORS::WHITE},
    {TEAM_ID::MILWAUKEE_BREWERS, COLORS::YELLOW},
    {TEAM_ID::MINNESOTA_TWINS, COLORS::RED},
    {TEAM_ID::NEW_YORK_METS, COLORS::NAVY_BLUE},
    {TEAM_ID::NEW_YORK_YANKEES, COLORS::BLACK},
    {TEAM_ID::OAKLAND_ATHLETICS, COLORS::YELLOW},
    {TEAM_ID::PHILADELPHIA_PHILLIES, COLORS::WHITE},
    {TEAM_ID::PITTSBURGH_PIRATES, COLORS::YELLOW},
    {TEAM_ID::SAN_DIEGO_PADRES, COLORS::YELLOW},
    {TEAM_ID::SAN_FRANCISCO_GIANTS, COLORS::ORANGE},
    {TEAM_ID::SEATTLE_MARINERS, COLORS::NAVY_BLUE},
    {TEAM_ID::ST_LOUIS_CARDINALS, COLORS::WHITE},
    {TEAM_ID::TAMPA_BAY_RAYS, COLORS::NAVY_BLUE},
    {TEAM_ID::TEXAS_RANGERS, COLORS::NAVY_BLUE},
    {TEAM_ID::TORONTO_BLUE_JAYS, COLORS::WHITE},
    {TEAM_ID::WASHINGTON_NATIONALS, COLORS::WHITE},
};

const int BASE_SIDE_LENGTH = 4;

const int BASES_TOP_X = 32;
const int BASES_TOP_Y = 11;

const uint16_t BASES_COLOR = COLORS::YELLOW;

#endif